<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 2,
                'uuid' => 'b38e1db9-9287-4831-aaa2-d4dd53c0f564',
                'collection_name' => 'image',
                'name' => 'loqo_light',
                'file_name' => 'loqo_light.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 7634,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 20:59:07',
                'updated_at' => '2023-08-22 20:59:07',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 3,
                'uuid' => '56848674-506a-43ca-b4b4-e2092c902bb4',
                'collection_name' => 'image',
                'name' => 'loqo_dark',
                'file_name' => 'loqo_dark.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 7612,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 20:59:25',
                'updated_at' => '2023-08-22 20:59:25',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 1,
                'uuid' => 'e7c4d839-c014-421b-b377-7ff98d3b8822',
                'collection_name' => 'image',
                'name' => 'favicon',
                'file_name' => 'favicon.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1301,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 21:03:39',
                'updated_at' => '2023-08-22 21:03:39',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 29,
                'uuid' => '6170fc4b-a990-4714-91be-3025e87259f9',
                'collection_name' => 'image',
                'name' => '01',
                'file_name' => '01.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 418932,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 21:46:16',
                'updated_at' => '2023-08-22 21:46:16',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 40,
                'uuid' => '2f3fa8a5-f605-4494-bbf4-af84c0d7585a',
                'collection_name' => 'image',
                'name' => 'schindler-villa-lift-hero 1',
                'file_name' => 'schindler-villa-lift-hero-1.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 189332,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:07:20',
                'updated_at' => '2023-08-22 22:07:20',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 39,
                'uuid' => '98ef3d26-42fc-4a1f-b697-426baf61df8a',
                'collection_name' => 'image',
                'name' => 'Open_lift_doors_iStock_000017211376_Medium 1',
                'file_name' => 'Open_lift_doors_iStock_000017211376_Medium-1.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 237760,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:07:28',
                'updated_at' => '2023-08-22 22:07:28',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 49,
                'uuid' => '7f91f8aa-fc91-4701-a92c-b59dff44e708',
                'collection_name' => 'image',
                'name' => 'paseenger-lift-for-hotel 1',
                'file_name' => 'paseenger-lift-for-hotel-1.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 441108,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:17:31',
                'updated_at' => '2023-08-22 22:17:31',
            ),
            7 => 
            array (
                'id' => 8,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 64,
                'uuid' => '7bace9ea-2553-4023-babb-91e7de69ff28',
                'collection_name' => 'image',
                'name' => '07',
                'file_name' => '07.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 8385,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:31:18',
                'updated_at' => '2023-08-22 22:31:18',
            ),
            8 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 61,
                'uuid' => '67ce5ba1-2930-4e71-914a-2dd21d1df7aa',
                'collection_name' => 'image',
                'name' => '09',
                'file_name' => '09.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 5029,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:31:26',
                'updated_at' => '2023-08-22 22:31:26',
            ),
            9 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 58,
                'uuid' => 'e4219768-eef0-453f-a0be-67691d2cb55c',
                'collection_name' => 'image',
                'name' => '08',
                'file_name' => '08.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 3047,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:31:34',
                'updated_at' => '2023-08-22 22:31:34',
            ),
            10 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 55,
                'uuid' => 'ee6b6025-f973-4889-b1b3-3e35355c5952',
                'collection_name' => 'image',
                'name' => '02',
                'file_name' => '02.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 4723,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-22 22:31:42',
                'updated_at' => '2023-08-22 22:31:42',
            ),
            11 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 72,
                'uuid' => '5ed70c8d-6dfc-446d-addb-972ebdcd2ecd',
                'collection_name' => 'image',
                'name' => '01',
                'file_name' => '01.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 2472,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 09:11:52',
                'updated_at' => '2023-08-23 09:11:52',
            ),
            12 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 75,
                'uuid' => 'd094f56c-4d05-4971-a91a-b5474dcff591',
                'collection_name' => 'image',
                'name' => '02',
                'file_name' => '02.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1683,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 09:12:00',
                'updated_at' => '2023-08-23 09:12:00',
            ),
            13 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 78,
                'uuid' => '3624409e-d19c-4871-8b19-6ab063bdbf01',
                'collection_name' => 'image',
                'name' => '03',
                'file_name' => '03.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 2583,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 09:12:12',
                'updated_at' => '2023-08-23 09:12:12',
            ),
            14 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 81,
                'uuid' => 'ce126784-8fc1-4b04-887f-6875bf631b72',
                'collection_name' => 'image',
                'name' => '04',
                'file_name' => '04.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 2653,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 09:12:19',
                'updated_at' => '2023-08-23 09:12:19',
            ),
            15 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\Team',
                'model_id' => 1,
                'uuid' => '7e290c66-7456-463c-bd9b-db70afe04188',
                'collection_name' => 'file',
                'name' => '08da70696b9ef19e072c9747e28e6ed8',
                'file_name' => '08da70696b9ef19e072c9747e28e6ed8.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 880071,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:55:29',
                'updated_at' => '2023-08-23 11:55:29',
            ),
            16 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\Team',
                'model_id' => 2,
                'uuid' => '2dd307c1-3a81-4681-aac8-bf92a6a8a929',
                'collection_name' => 'file',
                'name' => 'c386627be231f97602b5bb54dba1257f',
                'file_name' => 'c386627be231f97602b5bb54dba1257f.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 827650,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:55:49',
                'updated_at' => '2023-08-23 11:55:49',
            ),
            17 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\Team',
                'model_id' => 3,
                'uuid' => 'e0bb87a4-0760-46d8-b28e-9628fff901d3',
                'collection_name' => 'file',
                'name' => '30d4a7c7dff4f208b75289bb33ccbf5d',
                'file_name' => '30d4a7c7dff4f208b75289bb33ccbf5d.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 2081336,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:56:06',
                'updated_at' => '2023-08-23 11:56:06',
            ),
            18 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\Feature',
                'model_id' => 1,
                'uuid' => '62905cdf-2d0b-4353-a257-4483d275449e',
                'collection_name' => 'file',
                'name' => 'Frame',
                'file_name' => 'Frame.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 7077,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:59:10',
                'updated_at' => '2023-08-23 11:59:10',
            ),
            19 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Feature',
                'model_id' => 2,
                'uuid' => 'fc7f420b-c06a-47ef-8622-2ebf78cfb344',
                'collection_name' => 'file',
            'name' => 'Frame (1)',
            'file_name' => 'Frame-(1).svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 7304,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:59:20',
                'updated_at' => '2023-08-23 11:59:20',
            ),
            20 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\Feature',
                'model_id' => 3,
                'uuid' => '92860ec3-41be-443e-89c8-06caeded1ff9',
                'collection_name' => 'file',
            'name' => 'Frame (2)',
            'file_name' => 'Frame-(2).svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 8962,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:59:32',
                'updated_at' => '2023-08-23 11:59:32',
            ),
            21 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Feature',
                'model_id' => 4,
                'uuid' => '2254ddaf-ca71-42b5-8dce-8900beeae76a',
                'collection_name' => 'file',
            'name' => 'Frame (3)',
            'file_name' => 'Frame-(3).svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 11034,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:59:45',
                'updated_at' => '2023-08-23 11:59:45',
            ),
            22 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Feature',
                'model_id' => 5,
                'uuid' => '1eaab9ea-616e-4d00-96db-1af07e9db0eb',
                'collection_name' => 'file',
            'name' => 'Frame (4)',
            'file_name' => 'Frame-(4).svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 15495,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 11:59:57',
                'updated_at' => '2023-08-23 11:59:57',
            ),
            23 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Feature',
                'model_id' => 6,
                'uuid' => '69bb535d-0da9-42f1-9609-7007c3b19612',
                'collection_name' => 'file',
            'name' => 'Frame (5)',
            'file_name' => 'Frame-(5).svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 7307,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:00:10',
                'updated_at' => '2023-08-23 12:00:10',
            ),
            24 => 
            array (
                'id' => 25,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 1,
                'uuid' => '2e8d22dc-0db0-4548-aaa7-da2eb77bbc86',
                'collection_name' => 'images',
                'name' => '48a426f1870a0fe6f76302c6f1bb21f9',
                'file_name' => '48a426f1870a0fe6f76302c6f1bb21f9.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1497365,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:02:44',
                'updated_at' => '2023-08-23 12:02:44',
            ),
            25 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\Blog',
                'model_id' => 1,
                'uuid' => 'd792f41d-8fe0-4a3b-b30b-55918ca79945',
                'collection_name' => 'file',
                'name' => 'bd4503746966f9807259f5a4286e84b6',
                'file_name' => 'bd4503746966f9807259f5a4286e84b6.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1081145,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:43:16',
                'updated_at' => '2023-08-23 12:43:16',
            ),
            26 => 
            array (
                'id' => 27,
                'model_type' => 'App\\Models\\Blog',
                'model_id' => 2,
                'uuid' => '5045e953-0375-4f06-b9ae-753c555181e3',
                'collection_name' => 'file',
                'name' => '48a426f1870a0fe6f76302c6f1bb21f9',
                'file_name' => '48a426f1870a0fe6f76302c6f1bb21f9.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1497365,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:44:05',
                'updated_at' => '2023-08-23 12:44:05',
            ),
            27 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\Portfolio',
                'model_id' => 1,
                'uuid' => '841a4141-ab3f-4a12-9ea4-c111910c3d30',
                'collection_name' => 'images',
                'name' => 'f6ab42173ee5b61276c110054b4de833',
                'file_name' => 'f6ab42173ee5b61276c110054b4de833.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 48282,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:45:45',
                'updated_at' => '2023-08-23 12:45:45',
            ),
            28 => 
            array (
                'id' => 29,
                'model_type' => 'App\\Models\\Portfolio',
                'model_id' => 2,
                'uuid' => 'b1cca2b3-ba17-4239-9888-0fb17a5cc5a1',
                'collection_name' => 'images',
                'name' => '00e0ae3e41dc9f1df8a430bb1fce9d16',
                'file_name' => '00e0ae3e41dc9f1df8a430bb1fce9d16.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 240267,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:46:19',
                'updated_at' => '2023-08-23 12:46:19',
            ),
            29 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 2,
                'uuid' => '04000302-83ff-4c46-9186-a1f16d550723',
                'collection_name' => 'images',
                'name' => 'bd4503746966f9807259f5a4286e84b6',
                'file_name' => 'bd4503746966f9807259f5a4286e84b6.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1081145,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 12:47:06',
                'updated_at' => '2023-08-23 12:47:06',
            ),
            30 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\Service',
                'model_id' => 1,
                'uuid' => '1558f315-278d-40a7-9be8-be58bb427f0e',
                'collection_name' => 'file',
                'name' => '48a426f1870a0fe6f76302c6f1bb21f9',
                'file_name' => '48a426f1870a0fe6f76302c6f1bb21f9.jpeg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1497365,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 14:26:11',
                'updated_at' => '2023-08-23 14:26:11',
            ),
            31 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 93,
                'uuid' => 'd88bd4f5-8872-4325-acbc-787e8e023c82',
                'collection_name' => 'image',
                'name' => '04',
                'file_name' => '04.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 74064,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:07:31',
                'updated_at' => '2023-08-23 16:07:31',
            ),
            32 => 
            array (
                'id' => 33,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 94,
                'uuid' => 'd0900035-7248-4ae9-87c7-e42a4281f9bd',
                'collection_name' => 'image',
                'name' => '05',
                'file_name' => '05.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 33590,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:07:38',
                'updated_at' => '2023-08-23 16:07:38',
            ),
            33 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 98,
                'uuid' => 'fd971d11-b46a-484a-a5c1-7756d02c1b8a',
                'collection_name' => 'image',
                'name' => '13',
                'file_name' => '13.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 73687,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:10:24',
                'updated_at' => '2023-08-23 16:10:24',
            ),
            34 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 102,
                'uuid' => 'df69927e-6dc2-4397-ba9d-20e23aa6d820',
                'collection_name' => 'image',
                'name' => '01',
                'file_name' => '01.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 50259,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:20:28',
                'updated_at' => '2023-08-23 16:20:28',
            ),
            35 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 103,
                'uuid' => 'add5971d-f9b1-45fb-8814-d1f6a5f811d6',
                'collection_name' => 'image',
                'name' => '02',
                'file_name' => '02.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 60216,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:20:36',
                'updated_at' => '2023-08-23 16:20:36',
            ),
            36 => 
            array (
                'id' => 37,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 104,
                'uuid' => '3f978d32-0797-4461-87f7-a477595cdf35',
                'collection_name' => 'image',
                'name' => '03',
                'file_name' => '03.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 75797,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:20:43',
                'updated_at' => '2023-08-23 16:20:43',
            ),
            37 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 105,
                'uuid' => 'c0b4f8d0-051d-4874-b378-6f5e34a15c59',
                'collection_name' => 'image',
                'name' => '01',
                'file_name' => '01.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1510,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:20:50',
                'updated_at' => '2023-08-23 16:20:50',
            ),
            38 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 106,
                'uuid' => '29b91e81-8811-4659-97b2-e850902244e3',
                'collection_name' => 'image',
                'name' => '02',
                'file_name' => '02.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1439,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:21:02',
                'updated_at' => '2023-08-23 16:21:02',
            ),
            39 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 107,
                'uuid' => '8d47cb16-f854-4cba-bdaa-669860a857d5',
                'collection_name' => 'image',
                'name' => '03',
                'file_name' => '03.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 1443,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-23 16:21:12',
                'updated_at' => '2023-08-23 16:21:12',
            ),
            40 => 
            array (
                'id' => 41,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 123,
                'uuid' => '6b215efa-cce4-423f-8a33-2d171511f386',
                'collection_name' => 'image',
                'name' => 'breadcrumb',
                'file_name' => 'breadcrumb.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 176582,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:27:42',
                'updated_at' => '2023-08-24 10:27:42',
            ),
            41 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 124,
                'uuid' => '5ede6112-8865-407c-a187-c452df9124af',
                'collection_name' => 'image',
                'name' => 'breadcrumb',
                'file_name' => 'breadcrumb.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 176582,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:27:50',
                'updated_at' => '2023-08-24 10:27:50',
            ),
            42 => 
            array (
                'id' => 43,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 125,
                'uuid' => 'd5cfc489-bdf6-40b9-aef1-baff08a8b9f0',
                'collection_name' => 'image',
                'name' => 'breadcrumb',
                'file_name' => 'breadcrumb.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 176582,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:27:59',
                'updated_at' => '2023-08-24 10:27:59',
            ),
            43 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 128,
                'uuid' => '963ceccd-7faa-49d7-b91c-f937ef3b9cae',
                'collection_name' => 'image',
                'name' => 'breadcrumb',
                'file_name' => 'breadcrumb.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 176582,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:28:06',
                'updated_at' => '2023-08-24 10:28:06',
            ),
            44 => 
            array (
                'id' => 45,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 127,
                'uuid' => 'c224c42b-fd1d-448a-a9bf-0d7fcd5beab3',
                'collection_name' => 'image',
                'name' => 'breadcrumb',
                'file_name' => 'breadcrumb.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 176582,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:28:14',
                'updated_at' => '2023-08-24 10:28:14',
            ),
            45 => 
            array (
                'id' => 46,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 126,
                'uuid' => 'fb9e3141-d1e4-4a7e-a60c-960e09a14bf1',
                'collection_name' => 'image',
                'name' => 'breadcrumb',
                'file_name' => 'breadcrumb.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 176582,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:28:25',
                'updated_at' => '2023-08-24 10:28:25',
            ),
            46 => 
            array (
                'id' => 47,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 133,
                'uuid' => 'a91706ff-03f4-4190-80bf-70695465cfb6',
                'collection_name' => 'image',
                'name' => '09',
                'file_name' => '09.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 3727,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:29:20',
                'updated_at' => '2023-08-24 10:29:20',
            ),
            47 => 
            array (
                'id' => 48,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 134,
                'uuid' => 'b27f7252-d507-49c7-a4b3-a58bda6ff7f1',
                'collection_name' => 'image',
                'name' => '10',
                'file_name' => '10.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 3185,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:29:32',
                'updated_at' => '2023-08-24 10:29:32',
            ),
            48 => 
            array (
                'id' => 49,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 135,
                'uuid' => '0b76abb3-fd4c-4578-baae-88923ffd80b7',
                'collection_name' => 'image',
                'name' => '11',
                'file_name' => '11.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 7631,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:29:43',
                'updated_at' => '2023-08-24 10:29:43',
            ),
            49 => 
            array (
                'id' => 50,
                'model_type' => 'App\\Models\\Setting',
                'model_id' => 136,
                'uuid' => '9e823385-d0df-4bd0-ab09-e9b7f3acf9b1',
                'collection_name' => 'image',
                'name' => '12',
                'file_name' => '12.svg',
                'mime_type' => 'image/svg+xml',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 6500,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2023-08-24 10:29:55',
                'updated_at' => '2023-08-24 10:29:55',
            ),
            50 => 
            array (
                'id' => 51,
                'model_type' => 'App\\Models\\Service',
                'model_id' => 1,
                'uuid' => '74843adf-a14d-4edd-8ee9-91e6bcc0d8f0',
                'collection_name' => 'file',
                'name' => 'unsplash_M2uJLV9VPuo',
                'file_name' => 'unsplash_M2uJLV9VPuo.png',
                'mime_type' => 'image/png',
                'disk' => 'media',
                'conversions_disk' => 'media',
                'size' => 747176,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2023-08-27 02:03:57',
                'updated_at' => '2023-08-27 02:03:57',
            ),
        ));
        
        
    }
}