on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    if: ${{ !contains(github.event.head_commit.message, '[ftp]') }}
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Copy .env
      #   run: |
      #     php -r "file_exists('.env') || copy('.env.example', '.env');"
      #     echo DB_USERNAME=${{ secrets.SSH_USER }} >> .env
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Retrive directory
        run: |
          search_dir="$PWD"
          for entry in "$search_dir"/*
          do
            echo "$entry"
          done
      - name: Deploy with rsync
        run: rsync --modify-window=1 --update -avz --progress ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/domains/regal.thejavachip.com